name: cd phase
on:
    push:
        branches:
            - main
env:
    HUSKY: 0
    VITE_API_URL: ${{secrets.VITE_API_URL}}
    VITE_CLOUDINARY_CLOUD_NAME: ${{secrets.VITE_CLOUDINARY_CLOUD_NAME}}
    VITE_UPLOAD_PRESET_AVATAR: ${{secrets.VITE_UPLOAD_PRESET_AVATAR}}
    VITE_GOOGLE_AI_KEY: ${{secrets.VITE_GOOGLE_AI_KEY}}
    VITE_PAYMENT_BANK_ID: ${{secrets.VITE_PAYMENT_BANK_ID}}
    VITE_PAYMENT_BANK_ACCOUNT_NO: ${{secrets.VITE_PAYMENT_BANK_ACCOUNT_NO}}
    VITE_WS_URL: ${{secrets.VITE_WS_URL}}

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Pre-build client
              run: |
                  cd benkyo-client
                  envsubst < .env.example > .env
                  cat .env
            - name: Build image
              run: |
                  docker build ./benkyo-client/ -t ${{secrets.DOCKER_HUB_USERNAME}}/benkyo-fe:latest
                  docker build ./benkyo-server/ -t ${{secrets.DOCKER_HUB_USERNAME}}/benkyo-be:latest
            - name: Push image to docker dockerhub
              run: |
                  docker login -u ${{secrets.DOCKER_HUB_USERNAME}} -p ${{secrets.DOCKER_HUB_TOKEN}}
                  docker push ${{secrets.DOCKER_HUB_USERNAME}}/benkyo-fe:latest
                  docker push ${{secrets.DOCKER_HUB_USERNAME}}/benkyo-be:latest
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        needs: publish

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{secrets.SSH_PRIVATE_KEY }}

            - name: Copy docker-compose.yml
              run: scp -o StrictHostKeyChecking=no -r docker-compose.yml ${{secrets.SSH_USERNAME}}@${{secrets.SSH_HOST}}:/home/${{secrets.SSH_USERNAME}}/benkyo/docker-compose.yml

            - name: Deploy with docker-compose
              run: |
                  ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
                  cd /home/${{ secrets.SSH_USERNAME }}/benkyo
                  sudo docker-compose down --rmi all
                  sudo docker-compose up -d
                  EOF
